name: .NET Core

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  AZURE_WEBAPP_NAME: webgithubdemodev01    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.101'           # set this to the dot net version to use
  VAR_BRANCH: 'Develop'           # set this to the dot net version to use

jobs:
  build:

    runs-on: ubuntu-latest
    # environment: Desarrollo

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Imprimir
      run: echo ${{ env.VAR_BRANCH  }} - ${{ secrets.VAR_BRANCH  }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o demonetcore
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: demonetcore
        
  dev-release:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs: build
    # environment: Desarrollo
    steps:
    - name: Download math result for job 2
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: ${{ github.workspace }}
        
  prod-release:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: build
    # environment: Desarrollo
    steps:
    - name: Download math result for job 2
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: ${{ github.workspace }}
